// Contract configuration for FernetBarato
export const CONTRACT_ADDRESS = "0x0434f02eebb4546ce6232bf1743c8e5a2a534610bc0305a55c5412c2b85cbbca";

export const CONTRACT_ABI = [
   {
      "type":"impl",
      "name":"FernetBaratoImpl",
      "interface_name":"fernet_barato::IFernetBarato"
   },
   {
      "type":"struct",
      "name":"core::byte_array::ByteArray",
      "members":[
         {
            "name":"data",
            "type":"core::array::Array::<core::bytes_31::bytes31>"
         },
         {
            "name":"pending_word",
            "type":"core::felt252"
         },
         {
            "name":"pending_word_len",
            "type":"core::integer::u32"
         }
      ]
   },
   {
      "type":"struct",
      "name":"fernet_barato::Store",
      "members":[
         {
            "name":"id",
            "type":"core::felt252"
         },
         {
            "name":"name",
            "type":"core::byte_array::ByteArray"
         },
         {
            "name":"address",
            "type":"core::byte_array::ByteArray"
         },
         {
            "name":"hours",
            "type":"core::byte_array::ByteArray"
         },
         {
            "name":"URI",
            "type":"core::byte_array::ByteArray"
         }
      ]
   },
   {
      "type":"struct",
      "name":"core::integer::u256",
      "members":[
         {
            "name":"low",
            "type":"core::integer::u128"
         },
         {
            "name":"high",
            "type":"core::integer::u128"
         }
      ]
   },
   {
      "type":"struct",
      "name":"fernet_barato::Price",
      "members":[
         {
            "name":"price",
            "type":"core::integer::u256"
         },
         {
            "name":"timestamp",
            "type":"core::integer::u64"
         }
      ]
   },
   {
      "type":"struct",
      "name":"fernet_barato::Report",
      "members":[
         {
            "name":"store_id",
            "type":"core::felt252"
         },
         {
            "name":"description",
            "type":"core::byte_array::ByteArray"
         },
         {
            "name":"submitted_at",
            "type":"core::integer::u64"
         },
         {
            "name":"submitted_by",
            "type":"core::starknet::contract_address::ContractAddress"
         }
      ]
   },
   {
      "type":"enum",
      "name":"core::bool",
      "variants":[
         {
            "name":"False",
            "type":"()"
         },
         {
            "name":"True",
            "type":"()"
         }
      ]
   },
   {
      "type":"struct",
      "name":"fernet_barato::Profile",
      "members":[
         {
            "name":"user_address",
            "type":"core::starknet::contract_address::ContractAddress"
         },
         {
            "name":"report_count",
            "type":"core::integer::u64"
         },
         {
            "name":"thanks_count",
            "type":"core::integer::u64"
         },
         {
            "name":"last_connected",
            "type":"core::integer::u64"
         }
      ]
   },
   {
      "type":"interface",
      "name":"fernet_barato::IFernetBarato",
      "items":[
         {
            "type":"function",
            "name":"add_store",
            "inputs":[
               {
                  "name":"name",
                  "type":"core::byte_array::ByteArray"
               },
               {
                  "name":"address",
                  "type":"core::byte_array::ByteArray"
               },
               {
                  "name":"hours",
                  "type":"core::byte_array::ByteArray"
               },
               {
                  "name":"URI",
                  "type":"core::byte_array::ByteArray"
               }
            ],
            "outputs":[
               {
                  "type":"core::felt252"
               }
            ],
            "state_mutability":"external"
         },
         {
            "type":"function",
            "name":"get_store",
            "inputs":[
               {
                  "name":"store_id",
                  "type":"core::felt252"
               }
            ],
            "outputs":[
               {
                  "type":"fernet_barato::Store"
               }
            ],
            "state_mutability":"view"
         },
         {
            "type":"function",
            "name":"edit_store",
            "inputs":[
               {
                  "name":"store_id",
                  "type":"core::felt252"
               },
               {
                  "name":"name",
                  "type":"core::byte_array::ByteArray"
               },
               {
                  "name":"address",
                  "type":"core::byte_array::ByteArray"
               },
               {
                  "name":"hours",
                  "type":"core::byte_array::ByteArray"
               },
               {
                  "name":"URI",
                  "type":"core::byte_array::ByteArray"
               }
            ],
            "outputs":[
               
            ],
            "state_mutability":"external"
         },
         {
            "type":"function",
            "name":"get_all_stores",
            "inputs":[
               
            ],
            "outputs":[
               {
                  "type":"core::array::Array::<fernet_barato::Store>"
               }
            ],
            "state_mutability":"view"
         },
         {
            "type":"function",
            "name":"update_price",
            "inputs":[
               {
                  "name":"store_id",
                  "type":"core::felt252"
               },
               {
                  "name":"new_price",
                  "type":"core::integer::u256"
               }
            ],
            "outputs":[
               
            ],
            "state_mutability":"external"
         },
         {
            "type":"function",
            "name":"get_current_price",
            "inputs":[
               {
                  "name":"store_id",
                  "type":"core::felt252"
               }
            ],
            "outputs":[
               {
                  "type":"fernet_barato::Price"
               }
            ],
            "state_mutability":"view"
         },
         {
            "type":"function",
            "name":"get_price_history",
            "inputs":[
               {
                  "name":"store_id",
                  "type":"core::felt252"
               }
            ],
            "outputs":[
               {
                  "type":"core::array::Array::<fernet_barato::Price>"
               }
            ],
            "state_mutability":"view"
         },
         {
            "type":"function",
            "name":"get_all_current_prices",
            "inputs":[
               
            ],
            "outputs":[
               {
                  "type":"core::array::Array::<(core::felt252, fernet_barato::Price)>"
               }
            ],
            "state_mutability":"view"
         },
         {
            "type":"function",
            "name":"submit_report",
            "inputs":[
               {
                  "name":"store_id",
                  "type":"core::felt252"
               },
               {
                  "name":"description",
                  "type":"core::byte_array::ByteArray"
               }
            ],
            "outputs":[
               
            ],
            "state_mutability":"external"
         },
         {
            "type":"function",
            "name":"get_reports",
            "inputs":[
               {
                  "name":"store_id",
                  "type":"core::felt252"
               }
            ],
            "outputs":[
               {
                  "type":"core::array::Array::<fernet_barato::Report>"
               }
            ],
            "state_mutability":"view"
         },
         {
            "type":"function",
            "name":"give_thanks",
            "inputs":[
               {
                  "name":"store_id",
                  "type":"core::felt252"
               }
            ],
            "outputs":[
               
            ],
            "state_mutability":"external"
         },
         {
            "type":"function",
            "name":"get_thanks_count",
            "inputs":[
               {
                  "name":"store_id",
                  "type":"core::felt252"
               }
            ],
            "outputs":[
               {
                  "type":"core::integer::u64"
               }
            ],
            "state_mutability":"view"
         },
         {
            "type":"function",
            "name":"has_user_thanked",
            "inputs":[
               {
                  "name":"store_id",
                  "type":"core::felt252"
               },
               {
                  "name":"user",
                  "type":"core::starknet::contract_address::ContractAddress"
               }
            ],
            "outputs":[
               {
                  "type":"core::bool"
               }
            ],
            "state_mutability":"view"
         },
         {
            "type":"function",
            "name":"add_admin",
            "inputs":[
               {
                  "name":"admin",
                  "type":"core::starknet::contract_address::ContractAddress"
               }
            ],
            "outputs":[
               
            ],
            "state_mutability":"external"
         },
         {
            "type":"function",
            "name":"remove_admin",
            "inputs":[
               {
                  "name":"admin",
                  "type":"core::starknet::contract_address::ContractAddress"
               }
            ],
            "outputs":[
               
            ],
            "state_mutability":"external"
         },
         {
            "type":"function",
            "name":"is_admin",
            "inputs":[
               {
                  "name":"user",
                  "type":"core::starknet::contract_address::ContractAddress"
               }
            ],
            "outputs":[
               {
                  "type":"core::bool"
               }
            ],
            "state_mutability":"view"
         },
         {
            "type":"function",
            "name":"create_profile",
            "inputs":[
               
            ],
            "outputs":[
               
            ],
            "state_mutability":"external"
         },
         {
            "type":"function",
            "name":"update_last_connected",
            "inputs":[
               
            ],
            "outputs":[
               
            ],
            "state_mutability":"external"
         },
         {
            "type":"function",
            "name":"get_profile",
            "inputs":[
               {
                  "name":"user",
                  "type":"core::starknet::contract_address::ContractAddress"
               }
            ],
            "outputs":[
               {
                  "type":"fernet_barato::Profile"
               }
            ],
            "state_mutability":"view"
         },
         {
            "type":"function",
            "name":"profile_exists",
            "inputs":[
               {
                  "name":"user",
                  "type":"core::starknet::contract_address::ContractAddress"
               }
            ],
            "outputs":[
               {
                  "type":"core::bool"
               }
            ],
            "state_mutability":"view"
         }
      ]
   },
   {
      "type":"constructor",
      "name":"constructor",
      "inputs":[
         {
            "name":"owner",
            "type":"core::starknet::contract_address::ContractAddress"
         }
      ]
   },
   {
      "type":"event",
      "name":"fernet_barato::FernetBarato::Event",
      "kind":"enum",
      "variants":[
         
      ]
   }
];